#!/usr/bin/env python3
from pathlib import Path
import json, re, shutil
APP=Path(__file__).resolve().parents[1]
BANK_ROOT=APP/'data/observation_banks/creative_arts/worlds/digital_art'
SUB_ROOT=BANK_ROOT/'subcategories'
RUNTIME_DIR=APP/'data/content/base_bundle/creative_arts/digital_art'

def sid(s): return re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')
def diff(i): return ('beginner',1) if i<40 else (('intermediate',2) if i<70 else (('advanced',3) if i<90 else ('expert',4)))
def distract(term,pool):
    out=[]
    for x,_ in pool:
        if x!=term and x not in out: out.append(x)
        if len(out)>=3: break
    while len(out)<3: out.append('Not '+term)
    return out
prefs={'preferred':['rapid_classification','signal_vs_noise','odd_one_out'],'secondary':['memory_cascade','sequence_reverse','pattern_continuation'],'rare':['spatial_recall','stroop_test'],'disabled':['math_surprise','risk_selection','reflex_tap','speed_sort']}
mechs=['rapid_classification','signal_vs_noise','stroop_test','odd_one_out','memory_cascade','sequence_reverse','pattern_continuation','spatial_recall']
subcats={
'Digital Painting':[('Layer','independent editable image stack'),('Brush Preset','saved brush behavior'),('Opacity','stroke or layer transparency'),('Blending Mode','layer color interaction rule'),('Clipping Mask','mask limiting paint to a shape'),('Alpha Lock','transparent pixel protection'),('Color Picker','tool for choosing color'),('Pressure Sensitivity','stylus force response'),('Smudge Tool','pixel dragging blend tool'),('Canvas Size','working image dimensions'),('Resolution','pixel detail level'),('Digital Glazing','transparent color layering'),('Texture Brush','brush with simulated grain'),('Undo History','reversible edit record'),('Reference Layer','visual guide layer'),('Line Stabilization','software stroke smoothing'),('Gradient Map','value-to-color mapping'),('Flat Colors','base color stage'),('Render Pass','light shadow polish stage'),('Canvas Rotation','temporary view rotation'),('Selection Tool','isolates image region'),('Lasso Tool','freeform selection tool'),('Brush Flow','paint buildup rate'),('Hard Round Brush','crisp circular brush'),('Soft Airbrush','diffuse shading brush')],
'Pixel Art':[('Pixel','smallest raster square'),('Sprite','small game-ready image'),('Tile','repeating map square'),('Tileset','collection of reusable tiles'),('Palette','limited color set'),('Dithering','pattern simulating extra tones'),('Anti-Aliasing','edge smoothing pixels'),('Nearest Neighbor','hard-pixel scaling'),('Subpixel','tiny movement implied by color'),('Idle Animation','standing loop'),('Walk Cycle','walking animation loop'),('Sprite Sheet','grid of animation frames'),('Silhouette Readability','clear small outline'),('Outline','border around sprite form'),('Cluster','connected pixel group'),('Banding','unwanted stair-step pixels'),('Hue Shifting','color hue changes in shade'),('Limited Palette','restricted color choice'),('Isometric Pixel Art','angled-grid pixel scene'),('Top-Down Sprite','above-view sprite'),('Side-View Sprite','profile-view sprite'),('Pixel Font','grid-based letters'),('1-Bit Art','two-color pixel art'),('8-Bit Style','retro low-color look'),('Frame Timing','animation frame duration')],
'Vector Art':[('Anchor Point','point controlling a path'),('Bezier Curve','handle-controlled curve'),('Handle','curve control arm'),('Path','vector line or shape'),('Stroke','visible path outline'),('Fill','inside color of shape'),('Pen Tool','precise path tool'),('Node Editing','adjusting vector points'),('Boolean Union','combining shapes'),('Boolean Subtract','cutting one shape from another'),('Scalable Graphic','resizes without pixelation'),('SVG','web vector file format'),('Icon Set','family of related symbols'),('Flat Illustration','simple shape illustration'),('Gradient Fill','smooth color transition'),('Clipping Path','path hiding outside art'),('Outline Mode','path-only view'),('Artboard','vector workspace area'),('Shape Builder','shape combining tool'),('Vector Mask','path-based mask'),('Corner Radius','rounding shape corners'),('Pathfinder','boolean shape tools'),('Compound Path','multiple paths as one'),('Export Scale','output size multiplier'),('Vector Logo','scalable logo artwork')],
'Concept Art':[('Mood Board','reference board for tone'),('Silhouette Exploration','black-shape design testing'),('Thumbnail Iteration','small idea sketching'),('Key Art','major mood image'),('Design Brief','visual problem instructions'),('Callout Sheet','labeled design details'),('Turnaround','front side back views'),('Prop Design','object design for characters'),('Vehicle Design','transport design'),('Creature Design','imaginary animal design'),('Costume Design','character clothing design'),('Environment Concept','location design image'),('Value Study','light-dark exploration'),('Color Script','sequence of color moods'),('Shape Language','meaning from shapes'),('Reference Gathering','collecting visual sources'),('Exploration Sheet','alternative design page'),('Final Render','polished presentation image'),('Production Painting','finished reference painting'),('Design Iteration','versioned visual revision'),('Worldbuilding','fictional visual logic'),('Character Lineup','characters shown together'),('Material Callout','surface material note'),('Scale Reference','object showing size'),('Visual Development','early project look design')],
'3D Art':[('Polygon','flat mesh face'),('Vertex','point in 3D space'),('Edge','line connecting vertices'),('Mesh','object made of faces'),('UV Map','2D surface layout'),('Texture Map','image on model surface'),('Normal Map','fake surface detail texture'),('Roughness Map','shine control texture'),('PBR Material','physically based material'),('Sculpting','digital clay modeling'),('Retopology','rebuilding clean topology'),('Rigging','adding animation bones'),('Skinning','binding mesh to rig'),('Keyframe Animation','timed pose animation'),('Subdivision Surface','mesh smoothing modifier'),('Boolean Modeling','cutting or combining forms'),('Extrusion','pulling geometry outward'),('Bevel','rounded or angled edge'),('Lighting Setup','placing scene lights'),('Render Engine','final image calculator'),('Viewport','interactive 3D workspace'),('Camera Object','virtual scene camera'),('Ambient Occlusion','contact crevice shadow'),('Baking','precomputing texture data'),('Wireframe','edge-only mesh view')],
'Character Art':[('Character Sheet','character reference page'),('Expression Sheet','emotion face sheet'),('Pose Sheet','body pose sheet'),('Turnaround','multi-angle character view'),('Silhouette','outer readable shape'),('Shape Language','personality through shapes'),('Costume Design','clothing for character'),('Prop Accessory','carried object detail'),('Color Palette','character identity colors'),('Character Archetype','familiar story role'),('Hero Design','protagonist visual design'),('Villain Design','antagonist visual design'),('Sidekick Design','supporting character design'),('Mascot','simple memorable character'),('Facial Features','identity-shaping face parts'),('Hair Shape','hair silhouette design'),('Gesture Pose','personality body pose'),('Proportion','body size relationship'),('Stylization','intentional non-realism'),('Anatomy Simplification','reduced body detail'),('Lineup','characters shown together'),('Model Packet','production reference package'),('Backstory Clue','visual history hint'),('Readability','instant design clarity'),('Appeal','visual charm and interest')],
'Environment Art':[('Establishing View','wide location view'),('Interior Environment','inside location design'),('Exterior Environment','outside location design'),('Set Dressing','storytelling object placement'),('Focal Area','main viewer target'),('Foreground Layer','nearest depth layer'),('Midground Layer','middle depth layer'),('Background Layer','distant depth layer'),('Scale Cue','object showing size'),('Atmosphere','mood from light and air'),('Biome','natural environment type'),('Architecture Style','building visual language'),('Lighting Mood','emotional light tone'),('Pathway','route guiding viewer'),('Landmark','recognizable location feature'),('Modular Asset','reusable scene piece'),('Hero Asset','important unique object'),('Texture Tiling','repeating surface image'),('Material Library','reusable surface set'),('Skybox','distant surrounding background'),('Matte Painting','painted environment extension'),('Worldbuilding Detail','culture or history clue'),('Silhouette Read','clear mass outline'),('Color Key','small color plan'),('Overpaint','paintover on rough or 3D base')],
'UI Art':[('Icon','small symbolic image'),('Button State','interaction visual version'),('HUD','in-game display overlay'),('Menu Screen','navigation choice screen'),('Wireframe','simple layout plan'),('Prototype','interactive test version'),('Visual Hierarchy','importance ordering'),('Affordance','visual interaction clue'),('Contrast Ratio','text-background readability'),('Typography Scale','organized text sizing'),('Grid System','column or row layout'),('Padding','space inside element'),('Margin','space outside element'),('Tap Target','touch interaction area'),('Navigation Bar','persistent navigation control'),('Modal Window','temporary focused layer'),('Tooltip','short contextual help'),('Progress Bar','completion indicator'),('Toggle Switch','binary on-off control'),('Slider','continuous value control'),('Input Field','text entry box'),('Design System','reusable component rules'),('Style Guide','visual consistency document'),('Responsive Layout','screen-adaptive interface'),('Accessibility State','support for varied needs')],
'Game Art':[('Sprite','2D game image'),('Tilemap','grid-based level art'),('Character Rig','bones controlling character'),('Animation Cycle','looping movement'),('Idle Animation','standing loop'),('Run Cycle','running loop'),('VFX','game visual effects'),('Particle Effect','many small moving elements'),('Environment Asset','game world object'),('Prop Asset','small scene object'),('Texture Atlas','combined asset image'),('Normal Map','fake light-detail texture'),('Low Poly','few-polygon style'),('High Poly','detailed bake source'),('LOD','level of detail'),('Hit Flash','damage feedback effect'),('Health Bar','remaining-health UI'),('Loot Icon','item image symbol'),('Concept Pass','early art proposal'),('Production Asset','final usable art'),('Prefab','reusable game object'),('Shader','material appearance program'),('Sprite Sheet','animation frame grid'),('Parallax Layer','depth-moving background'),('Collision Mask','invisible gameplay contact shape')],
'AI Art':[('Text Prompt','written generation instruction'),('Prompt Engineering','crafting prompts for output'),('Image Model','AI image generator'),('Seed','repeatable generation number'),('Inpainting','editing selected image area'),('Outpainting','extending image border'),('Style Transfer','applying one style to another image'),('Reference Image','image guiding generation'),('Control Map','pose or depth guide'),('Latent Space','compressed model possibility space'),('Dataset','training image collection'),('Bias','systematic output skew'),('Artifact','unwanted generation error'),('Upscaling','increasing resolution'),('Face Restoration','AI facial detail correction'),('Negative Prompt','what to avoid in prompt'),('Iteration','revised generation cycle'),('Model Fine-Tuning','training for a style'),('Ethical Attribution','credit and rights concern'),('Copyright Concern','legal training or output issue'),('Synthetic Image','computer-generated image'),('Human Curation','person selecting AI output'),('Prompt Drift','output leaving the request'),('Hallucinated Detail','invented incorrect detail'),('Generative Workflow','prompt edit and selection process')]
}

def build_trans(term, wrongs, prompt):
    return {m:{'prompt':prompt,'correct_answer':term,'wrong_answers':wrongs} for m in mechs}
SUB_ROOT.mkdir(parents=True,exist_ok=True)
if RUNTIME_DIR.exists(): shutil.rmtree(RUNTIME_DIR)
RUNTIME_DIR.mkdir(parents=True,exist_ok=True)
wm_path=BANK_ROOT/'world_manifest.json'; wm=json.load(open(wm_path))
for sc in wm['subcategories']: sc.update({'implemented_observations':100,'status':'complete','scenario_preferences':prefs})
wm['status']='complete'; json.dump(wm,open(wm_path,'w'),indent=2)
compiled=[]
for subname,pool in subcats.items():
    subid=sid(subname); obs=[]
    for i in range(100):
        term,clue=pool[i%len(pool)]; wrongs=distract(term,pool); label,tier=diff(i); oid=f'creative_arts_digital_art_{subid}_{i+1:04d}'; variant=i//len(pool)
        prompt=[f'Which {subname} term matches: {clue}?',f'In {subname}, what means {clue}?',f'Name the {subname} concept described as: {clue}.',f'Which {subname.lower()} term is {clue}?'][variant%4]
        knowledge={'domain':'digital_art','subcategory':subid,'term':term,'concept':term,'definition_clue':clue,'recognized_answer':term,'distractor_family':wrongs,'difficulty_tier':tier,'keywords':[subid,sid(term)],'prompt_variant':variant}
        transformations=build_trans(term,wrongs,prompt)
        obs.append({'observation_id':oid,'universe':'creative_arts','world':'digital_art','subcategory':subid,'difficulty':{'label':label,'tier':tier},'observation_type':'Rapid Recognition','base_fact':f'{term}: {clue}.','prompt':prompt,'correct_answer':term,'distractors':wrongs,'localization':{'prompt_key':oid+'_prompt','answer_key':oid+'_answer'},'knowledge':knowledge,'mechanic_transformations':transformations,'metadata':{'tags':knowledge['keywords'],'scenario_compatibility':prefs,'deterministic_seed_key':oid,'quality':{'recognition':5,'visual_presentation':5,'fast_comprehension':5,'replayability':5,'educational_value':5,'mobile_readability':5},'source_basis':'Digital art education reference set based on production fundamentals.','knowledge':knowledge,'mechanic_transformations':transformations}})
        for mech,rule in transformations.items(): compiled.append({'id':f'{oid}_{mech}','observation_id':oid,'universe':'creative_arts','world':'digital_art','subcategory':subid,'type':mech,'rules':{'prompt':prompt,'legacy_prompt':prompt,'correct_answer':term,'wrong_answers':wrongs},'presentation':{'title':f'Digital Art — {subname}','difficulty_tier':tier,'subcategory':subid,'observation_type':mech},'knowledge':knowledge,'metadata':{'source_observation_id':oid,'knowledge':knowledge,'mechanic_transformations':transformations,'built_by':'digital_art_state_machine_compiler'}})
    bank={'schema_version':1,'observation_bank_version':'creative_arts.v1.digital_art','universe':'creative_arts','world':'digital_art','subcategory':subid,'display_name':subname,'constraint_vector':{'core_concept_space':f'Digital art concepts bounded to {subname}.','allowed_elements':['digital art vocabulary','tools','workflows','visual production concepts'],'forbidden_elements':['temporary platform trends','unverified software rumors','celebrity gossip','opinion-only prompts'],'domain_anchors':['digital art production fundamentals','game and media art pipelines','visual design education vocabulary'],'mechanic_suitability_map':prefs},'scenario_preferences':prefs,'observations':obs}
    json.dump(bank,open(SUB_ROOT/f'{subid}.json','w'),indent=2,ensure_ascii=False)
json.dump(compiled,open(RUNTIME_DIR/'digital_art_observation_bank_compiled.json','w'),indent=2,ensure_ascii=False)
print('digital_art observations',sum(len(json.load(open(p))['observations']) for p in SUB_ROOT.glob('*.json')),'compiled',len(compiled))
