from pathlib import Path
import json, re, shutil

APP=Path('app')
BANK_ROOT=APP/'data/observation_banks/creative_arts/worlds/photography'
SUB_ROOT=BANK_ROOT/'subcategories'
RUNTIME_DIR=APP/'data/content/base_bundle/creative_arts/photography'

def sid(s): return re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')

def diff(i):
    return [('beginner',1)]*40 + [('intermediate',2)]*30 + [('advanced',3)]*20 + [('expert',4)]*10
DIFF=diff(0)

subcats = {
'Cameras': [
('DSLR','camera with mirror and optical viewfinder','camera body'),('Mirrorless Camera','interchangeable-lens camera without a reflex mirror','camera body'),('Point-and-Shoot','compact camera with fixed lens and automatic controls','camera body'),('Medium Format','camera system using a larger sensor or film area','camera body'),('Full-Frame Sensor','digital sensor about the size of 35mm film','sensor'),('APS-C Sensor','crop sensor smaller than full frame','sensor'),('Micro Four Thirds','compact interchangeable lens sensor format','sensor'),('Rangefinder','camera focused through a separate viewing window','camera body'),('Twin-Lens Reflex','camera with separate viewing and taking lenses','camera body'),('Instant Camera','camera that produces a physical print quickly','camera body'),('Film Camera','camera that records images on photographic film','camera body'),('Pinhole Camera','lensless camera using a tiny aperture','camera body'),('Action Camera','small rugged camera for movement and sports','camera body'),('View Camera','large camera with bellows and ground glass','camera body'),('Bridge Camera','fixed-lens camera between compact and DSLR styles','camera body'),('Shutter','mechanism controlling how long light reaches sensor','camera part'),('Aperture','lens opening controlling light and depth of field','camera setting'),('ISO','sensor sensitivity setting','camera setting'),('Viewfinder','device used to compose the image','camera part'),('Hot Shoe','mount for flash or accessories','camera part'),('Memory Card','storage card for digital images','camera part'),('Battery Grip','attachment adding battery capacity and grip','camera part'),('LCD Screen','rear display for menus and image review','camera part'),('Image Sensor','light-sensitive digital recording surface','camera part'),('RAW File','minimally processed image data file','file format')],
'Lenses': [
('Prime Lens','lens with one fixed focal length','lens type'),('Zoom Lens','lens with variable focal length','lens type'),('Wide-Angle Lens','lens with broad field of view','lens type'),('Telephoto Lens','lens that magnifies distant subjects','lens type'),('Macro Lens','lens designed for close-up detail','lens type'),('Fisheye Lens','ultra-wide lens with curved distortion','lens type'),('Tilt-Shift Lens','lens that shifts perspective or focus plane','lens type'),('Kit Lens','basic lens commonly bundled with a camera','lens type'),('Portrait Lens','lens suited to flattering faces','lens type'),('Pancake Lens','very thin compact lens','lens type'),('Focal Length','distance measure affecting angle of view','lens concept'),('Aperture Ring','lens control for aperture on some lenses','lens part'),('Lens Hood','attachment that reduces flare','lens accessory'),('Lens Flare','light artifact from strong light hitting lens','lens effect'),('Bokeh','blur quality of out-of-focus areas','lens effect'),('Depth of Field','range that appears acceptably sharp','lens concept'),('Focus Ring','manual control for focus distance','lens part'),('Autofocus Motor','mechanism that moves lens elements to focus','lens part'),('Image Stabilization','system reducing blur from camera shake','lens feature'),('Minimum Focus Distance','closest distance a lens can focus','lens concept'),('Aperture Blades','overlapping parts forming lens opening','lens part'),('Lens Mount','connection between lens and camera body','lens part'),('Filter Thread','front threads for screw-on filters','lens part'),('Teleconverter','accessory that increases effective focal length','lens accessory'),('Lens Element','piece of glass inside a lens','lens part')],
'Lighting': [
('Key Light','main light on the subject','lighting role'),('Fill Light','light that softens shadows','lighting role'),('Back Light','light from behind subject','lighting role'),('Rim Light','edge light outlining a subject','lighting role'),('Softbox','modifier that creates soft light','modifier'),('Umbrella','modifier that spreads or reflects light','modifier'),('Reflector','surface bouncing light back to subject','modifier'),('Diffuser','material that softens light','modifier'),('Hard Light','light with sharp shadows','light quality'),('Soft Light','light with gentle shadow edges','light quality'),('Golden Hour','warm light shortly after sunrise or before sunset','natural light'),('Blue Hour','cool light before sunrise or after sunset','natural light'),('Flash','brief artificial burst of light','light source'),('Strobe','powerful flash used in studio','light source'),('Continuous Light','light that stays on during shooting','light source'),('Catchlight','bright reflection in the eyes','portrait lighting'),('High-Key Lighting','bright low-contrast lighting style','lighting style'),('Low-Key Lighting','dark high-contrast lighting style','lighting style'),('Silhouette','dark subject against bright background','lighting effect'),('Ambient Light','existing light in a scene','light source'),('Color Temperature','warm or cool color of light','lighting concept'),('White Balance','camera setting neutralizing color cast','camera setting'),('Light Meter','device measuring light exposure','tool'),('Bounce Flash','flash reflected off a surface','technique'),('Three-Point Lighting','key fill and back light setup','lighting setup')],
'Composition': [
('Rule of Thirds','placing subjects along thirds grid','composition rule'),('Leading Lines','lines guiding the eye through image','composition tool'),('Framing','using elements to surround the subject','composition tool'),('Symmetry','balanced mirrored arrangement','composition principle'),('Negative Space','empty area around the subject','composition principle'),('Foreground','nearest area in a scene','spatial layer'),('Background','distant area behind subject','spatial layer'),('Focal Point','main area drawing attention','composition principle'),('Balance','visual weight across the frame','composition principle'),('Contrast','difference in tone color or texture','composition principle'),('Pattern','repeated visual elements','composition principle'),('Texture','surface quality shown visually','composition element'),('Depth','sense of near-to-far space','composition principle'),('Scale','size relationship between elements','composition principle'),('Cropping','choosing frame edges','composition tool'),('Diagonal Line','slanted line adding energy','composition element'),('Horizon Placement','where the horizon sits in frame','composition tool'),('Center Composition','subject placed in the middle','composition choice'),('Golden Ratio','proportional guide about 1:1.618','composition rule'),('Visual Rhythm','repeated elements creating movement','composition principle'),('Layering','stacking foreground middle background','composition tool'),('Point of View','camera position relative to subject','composition choice'),('Simplification','removing distractions from frame','composition tool'),('Juxtaposition','placing contrasting subjects together','composition tool'),('Visual Flow','path the eye follows through an image','composition principle')],
'Portrait Photography': [
('Headshot','close portrait focused on face','portrait type'),('Environmental Portrait','portrait showing subject in surroundings','portrait type'),('Candid Portrait','unposed natural portrait','portrait type'),('Studio Portrait','portrait made with controlled lighting','portrait type'),('Rembrandt Lighting','triangle of light on cheek','portrait lighting'),('Butterfly Lighting','shadow under nose from frontal high light','portrait lighting'),('Split Lighting','one side of face lit and one dark','portrait lighting'),('Loop Lighting','small nose shadow looping to side','portrait lighting'),('Catchlight','eye reflection adding life','portrait feature'),('Shallow Depth of Field','blurred background behind subject','portrait technique'),('Eye Focus','sharp focus on eyes','portrait technique'),('Pose','body position of subject','portrait element'),('Expression','face emotion or mood','portrait element'),('Background Blur','out-of-focus background','portrait technique'),('85mm Lens','classic flattering portrait focal length','portrait lens'),('Skin Tone','color rendering of skin','portrait concern'),('Fill Light','light used to soften facial shadows','portrait lighting'),('Key Light','main portrait light','portrait lighting'),('Reflector','bounces light onto face','portrait tool'),('Group Portrait','portrait of multiple people','portrait type'),('Self-Portrait','portrait made by photographer of self','portrait type'),('Profile Portrait','side-view portrait','portrait type'),('Three-Quarter Pose','body angled partly to camera','portrait pose'),('High-Key Portrait','bright low-shadow portrait','portrait style'),('Low-Key Portrait','dark dramatic portrait','portrait style')],
'Wildlife Photography': [
('Telephoto Lens','lens used for distant animals','wildlife tool'),('Hide','concealed place for photographing animals','field tool'),('Camouflage','blending into environment','field technique'),('Fast Shutter Speed','freezes animal motion','camera setting'),('Burst Mode','captures rapid series of frames','camera feature'),('Autofocus Tracking','focus follows moving subject','camera feature'),('Animal Behavior','actions and habits of animals','wildlife knowledge'),('Ethical Distance','space that avoids disturbing wildlife','ethics'),('Habitat','natural environment of species','wildlife concept'),('Golden Hour','warm low-angle natural light','natural light'),('Bird-in-Flight','bird photographed while flying','wildlife subject'),('Macro Wildlife','close-up small creatures','wildlife subject'),('Safari Photography','wildlife photography on safari','genre'),('Patience','waiting for natural behavior','field skill'),('Blind','portable shelter for concealment','field tool'),('Remote Camera','camera triggered from a distance','field tool'),('Camera Trap','motion-triggered wildlife camera','field tool'),('Panning','following motion with camera','motion technique'),('Silhouette','animal dark against bright background','lighting effect'),('Predator','animal that hunts others','wildlife role'),('Prey','animal hunted by predators','wildlife role'),('Migration','seasonal animal movement','wildlife behavior'),('Nesting','birds building or using nests','wildlife behavior'),('Conservation','protection of wildlife and habitats','ethics'),('Fieldcraft','outdoor skill for approaching wildlife','field skill')],
'Landscape Photography': [
('Tripod','stabilizes camera for landscape work','tool'),('Wide-Angle Lens','captures broad scenery','lens'),('Graduated ND Filter','darkens bright sky area','filter'),('Polarizing Filter','reduces glare and deepens sky','filter'),('Long Exposure','uses slow shutter for motion blur','technique'),('Golden Hour','warm light near sunrise or sunset','light'),('Blue Hour','cool twilight light','light'),('Foreground Interest','near object adding depth','composition'),('Leading Lines','guides eye through scene','composition'),('Horizon Line','divides sky and land','composition'),('Panorama','wide stitched landscape view','format'),('Seascape','landscape focused on sea or coast','subject'),('Mountain Scene','landscape focused on mountains','subject'),('Waterfall Blur','smooth water from long exposure','effect'),('HDR','combining exposures for tonal range','editing'),('Dynamic Range','span from shadows to highlights','camera concept'),('Aperture f/11','common setting for deep sharpness','setting'),('Hyperfocal Distance','focus distance maximizing depth','focus concept'),('Weather','atmosphere such as fog or storm','condition'),('Cloud Texture','visible cloud detail','subject element'),('Reflection','mirrored scene in water','composition'),('Natural Frame','trees or rocks framing scene','composition'),('Scale Figure','person used to show size','composition'),('Minimal Landscape','simple sparse scenic image','style'),('Astro-Landscape','night landscape with stars','genre')],
'Street Photography': [
('Candid Moment','unposed public moment','street concept'),('Decisive Moment','perfect instant of action and composition','street concept'),('Urban Geometry','shapes and lines in city scenes','composition'),('Reflections','city scenes mirrored in glass or water','composition'),('Street Portrait','portrait made in public space','genre'),('Juxtaposition','unexpected contrast between subjects','composition'),('Silhouette','dark figure against bright background','lighting'),('Layered Scene','multiple depth planes in street image','composition'),('Public Space','street square transit or sidewalk','setting'),('Zone Focusing','preset focus distance for quick shooting','technique'),('Small Camera','discreet camera for street work','tool'),('Black and White','monochrome street style','style'),('Gesture','expressive body movement','visual cue'),('Signage','text signs in urban image','street element'),('Crowd','many people in public scene','subject'),('Umbrella Scene','weather-driven street subject','subject'),('Crosswalk','pedestrian crossing visual pattern','setting'),('Window Reflection','reflection in storefront glass','composition'),('Shadow Play','strong shadows as subject','lighting'),('Street Vendor','vendor as urban subject','subject'),('Subway Scene','transit setting','setting'),('Market Scene','busy public commerce setting','setting'),('Ethics','respectful photographing in public','practice'),('Timing','waiting for the right moment','skill'),('Henri Cartier-Bresson','photographer linked to decisive moment','photographer')],
'Famous Photographers': [
('Ansel Adams','black-and-white landscapes of the American West','photographer'),('Dorothea Lange','Depression-era documentary portraits','photographer'),('Henri Cartier-Bresson','decisive moment street photography','photographer'),('Annie Leibovitz','celebrity portrait photography','photographer'),('Cindy Sherman','staged self-portrait series','photographer'),('Richard Avedon','fashion and portrait photography','photographer'),('Diane Arbus','portraits of people outside social norms','photographer'),('Robert Capa','war photography','photographer'),('Margaret Bourke-White','photojournalism and industrial imagery','photographer'),('Gordon Parks','documentary photography and civil rights imagery','photographer'),('Man Ray','surrealist photography and rayographs','photographer'),('Julia Margaret Cameron','soft-focus Victorian portraits','photographer'),('Edward Weston','modernist still lifes and nudes','photographer'),('Walker Evans','documentary images of American life','photographer'),('Berenice Abbott','New York city photography','photographer'),('Vivian Maier','street photography discovered after her death','photographer'),('Steve McCurry','color documentary portraiture','photographer'),('Sally Mann','family and Southern landscape photography','photographer'),('Sebastião Salgado','large-scale social documentary photography','photographer'),('Nan Goldin','intimate diaristic color photography','photographer'),('Eadweard Muybridge','motion studies with sequential photographs','photographer'),('Alfred Stieglitz','promoted photography as fine art','photographer'),('Imogen Cunningham','botanical and portrait photography','photographer'),('Weegee','flash crime-scene street photography','photographer'),('Yousuf Karsh','formal portraits of famous figures','photographer')],
'Editing': [
('Crop','change image framing','editing action'),('Exposure Adjustment','brighten or darken image','editing action'),('Contrast Adjustment','increase difference between light and dark','editing action'),('White Balance','correct color temperature','editing action'),('Saturation','increase or reduce color intensity','editing action'),('Vibrance','boost muted colors selectively','editing action'),('Sharpening','increase edge clarity','editing action'),('Noise Reduction','reduce grain or digital speckles','editing action'),('Cloning','copy pixels to remove distractions','editing action'),('Healing Brush','blend repair into surrounding pixels','editing action'),('Dodge','lighten selected areas','editing action'),('Burn','darken selected areas','editing action'),('Curves','tone control using a graph','editing tool'),('Levels','set black white and midtone points','editing tool'),('Masking','limit edits to selected areas','editing tool'),('Layer','stacked editable image component','editing concept'),('RAW Processing','developing minimally processed camera data','editing workflow'),('Color Grading','creative color styling','editing action'),('Black-and-White Conversion','remove color for monochrome image','editing action'),('HDR Merge','combine exposures for high dynamic range','editing workflow'),('Panorama Stitch','combine images into wide view','editing workflow'),('Lens Correction','fix distortion or vignetting','editing action'),('Retouching','polish portrait or product details','editing action'),('Export','save edited image for use','editing action'),('Metadata','embedded information such as date or camera','file concept')]
}

# prefs and generation helpers
structurals=['stroop_test','odd_one_out','memory_cascade','sequence_reverse','pattern_continuation','spatial_recall']

def prefs_for(name):
    n=name.lower()
    pref=['rapid_classification','signal_vs_noise','stroop_test']
    sec=['odd_one_out','memory_cascade','sequence_reverse']
    rare=['pattern_continuation','spatial_recall']
    dis=['math_surprise','risk_selection','reflex_tap','speed_sort']
    if 'lighting' in n or 'composition' in n: sec=['spatial_recall','odd_one_out','memory_cascade']; rare=['pattern_continuation','sequence_reverse']
    if 'editing' in n: sec=['sequence_reverse','memory_cascade','odd_one_out']; rare=['pattern_continuation','stroop_test']
    return {'preferred':pref,'secondary':sec,'rare':rare,'disabled':dis}

def diff(i):
    if i<40: return 'beginner',1
    if i<70: return 'intermediate',2
    if i<90: return 'advanced',3
    return 'expert',4

def distract(ans,pool):
    out=[]
    for x,_,_ in pool:
        if x!=ans and x not in out: out.append(x)
        if len(out)>=3: break
    while len(out)<3: out.append('Not '+ans)
    return out

def transformations(term, clue, category, wrongs, idx):
    return {
      'rapid_classification': {'prompt': f'Which term matches: {clue}?', 'correct_answer': term, 'wrong_answers': wrongs},
      'signal_vs_noise': {'prompt': f'Find: {term}', 'correct_answer': term, 'wrong_answers': wrongs},
      'stroop_test': {'prompt': term.upper(), 'correct_answer': 'COLOR_TASK', 'wrong_answers': []},
      'odd_one_out': {'prompt': f'Which item is not a {category}?', 'correct_answer': wrongs[0], 'wrong_answers': [term] + wrongs[1:]},
      'memory_cascade': {'prompt': f'Remember the {category} set.', 'sequence': [term, wrongs[0], wrongs[1]], 'correct_answer': term, 'wrong_answers': wrongs},
      'sequence_reverse': {'prompt': f'Reverse this {category} sequence.', 'sequence': [term, wrongs[0], wrongs[1]], 'correct_answer': ' → '.join([wrongs[1], wrongs[0], term]), 'wrong_answers': [' → '.join([term, wrongs[1], wrongs[0]]), ' → '.join([wrongs[0], term, wrongs[1]])]},
      'pattern_continuation': {'prompt': f'{category.title()} → {term} → ?', 'correct_answer': wrongs[0], 'wrong_answers': [wrongs[1], wrongs[2], term]},
      'spatial_recall': {'prompt': f'Recall where {term} appeared.', 'correct_answer': term, 'wrong_answers': wrongs, 'grid_hint': category}
    }


SUB_ROOT.mkdir(parents=True,exist_ok=True)
if RUNTIME_DIR.exists(): shutil.rmtree(RUNTIME_DIR)
RUNTIME_DIR.mkdir(parents=True,exist_ok=True)
compiled=[]
world_manifest=json.load(open(BANK_ROOT/'world_manifest.json'))
for sub in world_manifest['subcategories']:
    sub['implemented_observations']=100
    sub['status']='complete'
world_manifest['status']='complete'
json.dump(world_manifest, open(BANK_ROOT/'world_manifest.json','w'), indent=2)
for subname, pool in subcats.items():
    subid=sid(subname); prefs=prefs_for(subname); obs=[]
    for i in range(100):
        term, clue, category=pool[i%len(pool)]; wrongs=distract(term,pool); label,tier=diff(i); oid=f'creative_arts_photography_{subid}_{i+1:04d}'
        variant=i//len(pool)
        prompt_variants=[
            f'Which photography term matches: {clue}?',
            f'In {subname}, what means {clue}?',
            f'Name the {category} described as: {clue}.',
            f'Which {subname.lower()} concept is {clue}?'
        ]
        prompt=prompt_variants[variant % len(prompt_variants)]
        knowledge={'domain':'photography','subcategory':subid,'term':term,'concept':term,'definition_clue':clue,'recognized_answer':term,'distractor_family':wrongs,'difficulty_tier':tier,'keywords':[subid,sid(term),sid(category)],'category':category,'prompt_variant':variant}
        trans=transformations(term,clue,category,wrongs,i)
        # Ensure every mechanic transformation carries a unique source prompt for validators; builder uses knowledge.term where needed.
        for mech in trans:
            trans[mech]['source_prompt']=prompt
        obs.append({'observation_id':oid,'universe':'creative_arts','world':'photography','subcategory':subid,'difficulty':{'label':label,'tier':tier},'observation_type':'Rapid Recognition','base_fact':f'{term}: {clue}.','prompt':prompt,'correct_answer':term,'distractors':wrongs,'localization':{'prompt_key':oid+'_prompt','answer_key':oid+'_answer'},'knowledge':knowledge,'mechanic_transformations':trans,'metadata':{'tags':knowledge['keywords'],'scenario_compatibility':prefs,'deterministic_seed_key':oid,'quality':{'recognition':5,'visual_presentation':5,'fast_comprehension':5,'replayability':5,'educational_value':5,'mobile_readability':5},'source_basis':'Photography education reference set based on camera, lens, lighting, composition, genre, photographer, and editing fundamentals.','knowledge':knowledge,'mechanic_transformations':trans}})
        for mech, rule in trans.items():
            runtime_prompt = prompt
            compiled.append({'id':f'{oid}_{mech}','observation_id':oid,'universe':'creative_arts','world':'photography','subcategory':subid,'type':mech,'rules':{'prompt':runtime_prompt,'legacy_prompt':runtime_prompt,'correct_answer':rule.get('correct_answer',''),'wrong_answers':rule.get('wrong_answers',[])},'presentation':{'title':f'Photography — {subname}','difficulty_tier':tier,'subcategory':subid,'observation_type':mech},'knowledge':knowledge,'metadata':{'source_observation_id':oid,'knowledge':knowledge,'mechanic_transformations':trans,'built_by':'photography_state_machine_compiler'}})
    bank={'schema_version':1,'observation_bank_version':'creative_arts.v1.photography','universe':'creative_arts','world':'photography','subcategory':subid,'display_name':subname,'constraint_vector':{'core_concept_space':f'Photography concepts bounded to {subname}.','allowed_elements':['widely taught photography terms','equipment','techniques','recognized practitioners','visual principles'],'forbidden_elements':['temporary social media trends','brand rumors','overly niche gear trivia','opinion-only claims'],'domain_anchors':['museum/education photography vocabulary','camera craft fundamentals','publicly recognizable photography history'],'mechanic_suitability_map':prefs},'scenario_preferences':prefs,'observations':obs}
    json.dump(bank, open(SUB_ROOT/f'{subid}.json','w'), indent=2, ensure_ascii=False)
json.dump(compiled, open(RUNTIME_DIR/'photography_observation_bank_compiled.json','w'), indent=2, ensure_ascii=False)
print('photography observations',sum(len(json.load(open(p))['observations']) for p in SUB_ROOT.glob('*.json')),'compiled',len(compiled))
