from pathlib import Path
import json, re, shutil
APP=Path('/home/user/repo/app')
BANK_ROOT=APP/'data/observation_banks/creative_arts/worlds/drawing'
SUB_ROOT=BANK_ROOT/'subcategories'
RUNTIME_DIR=APP/'data/content/base_bundle/creative_arts/drawing'

def sid(s): return re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')
def diff(i): return ('beginner',1) if i<40 else (('intermediate',2) if i<70 else (('advanced',3) if i<90 else ('expert',4)))
def distract(term,pool):
    out=[]
    for x,_,_ in pool:
        if x!=term and x not in out: out.append(x)
        if len(out)>=3: break
    while len(out)<3: out.append('Not '+term)
    return out
prefs={'preferred':['rapid_classification','signal_vs_noise','odd_one_out'],'secondary':['memory_cascade','sequence_reverse','pattern_continuation'],'rare':['spatial_recall','stroop_test'],'disabled':['math_surprise','risk_selection','reflex_tap','speed_sort']}
subcats={
'Sketching': [('Gesture Sketch','quick drawing capturing overall action','sketching concept'),('Thumbnail Sketch','small rough idea drawing','sketching concept'),('Contour Sketch','drawing focused on outer edges','sketching concept'),('Blind Contour','contour drawing without looking at paper','sketching exercise'),('Loose Sketch','rough informal drawing','sketching style'),('Study Sketch','practice drawing for observation','sketching purpose'),('Life Sketch','drawing from a live subject','sketching subject'),('Urban Sketch','drawing scenes from city life','sketching genre'),('Field Sketch','drawing observations outdoors','sketching genre'),('Preliminary Sketch','early drawing before final artwork','sketching stage'),('Refined Sketch','cleaner developed sketch','sketching stage'),('Underdrawing','initial drawing beneath final media','sketching layer'),('Construction Lines','guidelines used to build forms','sketching tool'),('Blocking In','placing large shapes first','sketching process'),('Proportion Check','comparing sizes while drawing','sketching process'),('Negative Shape Sketch','drawing spaces around forms','sketching method'),('Value Sketch','small sketch planning lights and darks','sketching method'),('Compositional Sketch','sketch exploring layout','sketching purpose'),('Sketchbook','book used for regular drawing practice','sketching tool'),('Loose Line','relaxed expressive line','line quality'),('Exploratory Marks','test marks made while searching form','sketching process'),('Observation Sketch','drawing from direct looking','sketching method'),('Memory Sketch','drawing from remembered subject','sketching method'),('Speed Sketch','timed quick drawing','sketching exercise'),('Rough-In','first rough placement of forms','sketching stage')],
'Perspective': [('Horizon Line','eye-level line in perspective','perspective element'),('Vanishing Point','point where receding lines meet','perspective element'),('Orthogonal Lines','receding guide lines to vanishing point','perspective element'),('One-Point Perspective','perspective with one vanishing point','perspective type'),('Two-Point Perspective','perspective with two vanishing points','perspective type'),('Three-Point Perspective','perspective with three vanishing points','perspective type'),('Birds-Eye View','viewpoint looking down from above','perspective view'),('Worms-Eye View','viewpoint looking up from below','perspective view'),('Eye Level','height of viewer eyes','perspective concept'),('Foreshortening','shortening forms to show depth','perspective effect'),('Convergence','parallel edges appearing to meet','perspective effect'),('Picture Plane','flat imaginary drawing surface','perspective concept'),('Station Point','observer position in perspective','perspective concept'),('Linear Perspective','space built with receding lines','perspective system'),('Atmospheric Perspective','depth shown by fading color and contrast','perspective system'),('Overlapping Forms','depth shown by one form covering another','depth cue'),('Scale Change','objects shrink with distance','depth cue'),('Ellipses','circles seen in perspective','perspective shape'),('Perspective Grid','grid that follows perspective lines','perspective tool'),('Measuring Point','point used to transfer distances','perspective tool'),('Cone of Vision','area seen without distortion','perspective concept'),('Depth Cue','visual sign of near or far space','perspective concept'),('Ground Plane','surface objects rest on','perspective element'),('Verticals','upright lines in perspective drawing','perspective line'),('Cube Construction','building forms from boxes in space','perspective exercise')],
'Anatomy': [('Skull','bony structure of the head','anatomy structure'),('Rib Cage','chest structure protecting organs','anatomy structure'),('Pelvis','bowl-like hip structure','anatomy structure'),('Spine','column supporting torso and posture','anatomy structure'),('Clavicle','collarbone across upper chest','anatomy structure'),('Scapula','shoulder blade on upper back','anatomy structure'),('Humerus','upper arm bone','anatomy structure'),('Radius','forearm bone on thumb side','anatomy structure'),('Ulna','forearm bone on little-finger side','anatomy structure'),('Femur','upper leg bone','anatomy structure'),('Tibia','larger shin bone','anatomy structure'),('Fibula','smaller outer lower-leg bone','anatomy structure'),('Deltoid','shoulder muscle cap','muscle'),('Biceps','front upper arm muscle','muscle'),('Triceps','back upper arm muscle','muscle'),('Pectoral','chest muscle','muscle'),('Latissimus Dorsi','large back muscle','muscle'),('Trapezius','upper back and neck muscle','muscle'),('Abdominals','front torso muscles','muscle'),('Gluteus','buttock muscle group','muscle'),('Quadriceps','front thigh muscle group','muscle'),('Hamstrings','back thigh muscle group','muscle'),('Calf Muscle','back lower-leg muscle','muscle'),('Proportions','relative body measurements','anatomy concept'),('Landmarks','visible bony points used in figure drawing','anatomy concept')],
'Shading': [('Value Scale','range from light to dark','shading concept'),('Highlight','brightest light area','light value'),('Midtone','middle value between light and dark','light value'),('Core Shadow','darkest part of form shadow','shadow type'),('Cast Shadow','shadow thrown onto another surface','shadow type'),('Reflected Light','light bouncing into shadow','light effect'),('Terminator','edge where light turns into shadow','light boundary'),('Hatching','parallel lines for value','shading technique'),('Cross-Hatching','overlapping line sets for darker value','shading technique'),('Stippling','dots used to build value','shading technique'),('Blending','softening transitions between values','shading technique'),('Smudging','spreading graphite or charcoal','shading technique'),('Gradient','smooth value transition','shading concept'),('Hard Edge','sharp transition between values','edge type'),('Soft Edge','gradual transition between values','edge type'),('Form Shadow','shadow on the object itself','shadow type'),('Occlusion Shadow','dark contact shadow in tight spaces','shadow type'),('Light Source','origin direction of light','lighting concept'),('Tonal Drawing','drawing built mainly with values','drawing type'),('Chiaroscuro','strong contrast of light and dark','lighting style'),('High Contrast','large value difference','value concept'),('Low Contrast','small value difference','value concept'),('Graphite Shine','reflective surface from heavy pencil','material effect'),('Layered Shading','building values gradually','shading process'),('Kneaded Eraser Lift','lifting graphite to make light marks','shading tool')],
'Line Art': [('Contour Line','line describing the edge of a form','line type'),('Cross Contour','line wrapping across form surface','line type'),('Gesture Line','line expressing movement','line type'),('Line Weight','thickness or darkness of a line','line quality'),('Outline','line around outer edge','line type'),('Hatching Line','parallel marks for tone','line technique'),('Clean Line','smooth controlled line','line quality'),('Broken Line','line with gaps or interruptions','line quality'),('Expressive Line','line showing energy or emotion','line quality'),('Implied Line','suggested line not fully drawn','line concept'),('Silhouette','solid outer shape of subject','line concept'),('Inking','finalizing line art with ink','line process'),('Brush Pen','flexible pen for varied line weight','line tool'),('Technical Pen','consistent fine-line drawing pen','line tool'),('Nib Pen','dip pen point for ink drawing','line tool'),('Line Hierarchy','using varied line weight for depth','line concept'),('Tapered Line','line ending in a point','line quality'),('Bold Line','heavy dark line','line quality'),('Fine Line','thin delicate line','line quality'),('Lost and Found Edge','edge alternates visible and implied','line concept'),('Negative Line','line formed by surrounding shapes','line concept'),('Edge Control','deciding hard soft or missing edges','line concept'),('Ink Wash Line','line combined with diluted ink tone','line technique'),('Line Economy','using few lines effectively','line concept'),('Rhythmic Line','repeated line creating movement','line quality')],
'Cartoon Drawing': [('Exaggeration','pushing features beyond realism','cartoon principle'),('Squash and Stretch','shape change showing motion or impact','animation principle'),('Big Eyes','common cute character feature','cartoon feature'),('Simplified Shapes','building characters from simple forms','cartoon method'),('Expression Sheet','set of character facial expressions','cartoon tool'),('Turnaround','character views from multiple angles','cartoon tool'),('Silhouette Readability','clear character shape at a glance','cartoon principle'),('Pose Line','line showing action through body','cartoon method'),('Caricature','exaggerated likeness of a person','cartoon genre'),('Mascot Design','simple memorable character identity','cartoon genre'),('Speech Bubble','shape containing dialogue','comic element'),('Motion Lines','lines showing movement','cartoon symbol'),('Impact Star','burst shape showing hit or surprise','cartoon symbol'),('Simplified Hands','reduced hand detail in cartoons','cartoon feature'),('Bean Body','simple bean-shaped torso','cartoon construction'),('Rubber Hose Style','old cartoon bendy-limb style','cartoon style'),('Cute Proportions','large head and small body','cartoon style'),('Villain Shape Language','sharp forms suggesting danger','design concept'),('Hero Shape Language','stable strong forms suggesting trust','design concept'),('Sidekick Design','supporting character with contrast','cartoon role'),('Facial Iconography','symbols for emotions like sweat drops','cartoon language'),('Mouth Shape','cartoon mouth used for expression','cartoon feature'),('Eye Shape','eyes used to signal personality','cartoon feature'),('Prop Design','objects designed for character use','cartoon design'),('Model Sheet','reference sheet for consistent drawing','cartoon tool')],
'Comic Drawing': [('Panel','single framed unit of comic action','comic element'),('Gutter','space between comic panels','comic element'),('Speech Balloon','bubble containing spoken dialogue','comic element'),('Thought Balloon','bubble showing inner thought','comic element'),('Caption Box','box with narration or context','comic element'),('Sound Effect Lettering','drawn words for sounds','comic element'),('Splash Page','full-page dramatic image','comic format'),('Page Layout','arrangement of panels on a page','comic structure'),('Panel Flow','path reader follows across panels','comic structure'),('Close-Up Panel','panel focused on detail or face','shot type'),('Establishing Panel','panel showing location or context','shot type'),('Speed Lines','lines showing fast movement','comic effect'),('Action Pose','pose expressing movement or force','comic drawing'),('Inking','final line pass in comics','comic process'),('Penciling','rough drawing stage before inks','comic process'),('Lettering','placing dialogue and text','comic process'),('Flatting','base color separation stage','comic process'),('Colorist','artist who applies comic color','comic role'),('Penciler','artist drawing page pencils','comic role'),('Inker','artist refining line art in ink','comic role'),('Sequential Art','art arranged to show sequence','comic concept'),('Manga Paneling','comic page conventions in manga','comic style'),('Chibi','small cute exaggerated character style','comic style'),('Screen Tone','dot or pattern shading used in manga','comic tool'),('Visual Onomatopoeia','drawn sound words integrated in art','comic language')],
'Technical Drawing': [('Orthographic Projection','front top and side views','technical system'),('Isometric Drawing','3D object drawn with equal axes','technical system'),('Blueprint','technical plan drawing','technical document'),('Dimension Line','line showing measured distance','technical element'),('Scale Drawing','drawing made at proportional size','technical concept'),('Section View','cutaway view showing interior','technical view'),('Exploded View','parts separated to show assembly','technical view'),('Drafting Compass','tool for circles and arcs','drafting tool'),('T-Square','tool for horizontal drafting lines','drafting tool'),('Triangle Ruler','tool for angled drafting lines','drafting tool'),('French Curve','template for smooth curves','drafting tool'),('Title Block','information area on drawing sheet','technical element'),('Hidden Line','dashed line for unseen edge','technical line'),('Centerline','line marking center axis','technical line'),('Leader Line','line pointing to a note','technical line'),('Tolerance','allowed measurement variation','technical concept'),('CAD','computer-aided design drawing','technical tool'),('Plan View','view from above','technical view'),('Elevation View','front or side vertical view','technical view'),('Assembly Drawing','drawing showing parts together','technical document'),('Detail Drawing','drawing of one specific part','technical document'),('Cross Section','slice through an object','technical view'),('Projection Line','line transferring features between views','technical line'),('Scale Bar','visual reference for measurement scale','technical element'),('Drafting Pencil','pencil used for precise technical drawing','drafting tool')],
'Figure Drawing': [('Gesture Drawing','quick drawing of body action','figure method'),('Long Pose','extended figure drawing session','figure method'),('Short Pose','brief timed figure drawing','figure method'),('Contrapposto','weight shifted onto one leg','figure pose'),('Line of Action','main flow of body movement','figure concept'),('Proportion','relative body measurements in figure drawing','figure concept'),('Foreshortening','body parts shortened by perspective','figure concept'),('Mass Gesture','gesture using large body forms','figure method'),('Mannequinization','simplifying figure into forms','figure method'),('Plumb Line','vertical alignment check','figure tool'),('Weight Bearing Leg','leg carrying body weight','figure concept'),('Balance Point','center of body stability','figure concept'),('Torso Block','simplified chest and pelvis forms','figure construction'),('Head Unit','using head length as measurement','figure measurement'),('Negative Shape','space around figure used for accuracy','figure method'),('Silhouette Gesture','outside shape capturing pose','figure method'),('Anatomical Landmark','visible point guiding body structure','figure concept'),('Rhythm Line','flowing line connecting forms','figure concept'),('Foreshortened Limb','limb projecting toward viewer','figure challenge'),('Figure Ground','relationship between figure and background','composition concept'),('Drapery Study','drawing cloth on the figure','figure subject'),('Life Model','person posing for drawing','figure subject'),('Skeleton Landmarks','bony points visible on body','figure anatomy'),('Muscle Group','visible group shaping body form','figure anatomy'),('Pose Flow','overall directional movement of pose','figure concept')],
'Drawing Tools': [('Graphite Pencil','common pencil drawing tool','drawing tool'),('Charcoal Stick','soft black drawing material','drawing tool'),('Conte Crayon','compressed drawing stick','drawing tool'),('Mechanical Pencil','pencil with replaceable lead','drawing tool'),('Kneaded Eraser','moldable eraser for lifting graphite','drawing tool'),('Vinyl Eraser','firm white eraser','drawing tool'),('Blending Stump','rolled paper tool for blending','drawing tool'),('Tortillon','small pointed blending tool','drawing tool'),('Sketchbook','book for drawing practice','drawing tool'),('Drawing Board','rigid support surface','drawing tool'),('Fixative','spray that protects dry media','drawing supply'),('Ink Pen','pen using ink for line work','drawing tool'),('Brush Pen','pen with flexible brush-like tip','drawing tool'),('Dip Pen','pen dipped into ink','drawing tool'),('Ruler','straightedge measuring tool','drawing tool'),('Compass','tool for drawing circles','drawing tool'),('Protractor','tool for measuring angles','drawing tool'),('Light Box','illuminated surface for tracing','drawing tool'),('Tracing Paper','transparent paper for copying lines','drawing supply'),('Bristol Board','smooth heavy drawing surface','drawing supply'),('Newsprint','cheap paper for practice drawing','drawing supply'),('Charcoal Paper','toothy paper for charcoal','drawing supply'),('Sandpaper Block','sharpens charcoal or pencil points','drawing tool'),('Pencil Sharpener','tool for sharpening pencil tips','drawing tool'),('Portfolio','case for storing finished drawings','drawing supply')]
}

def trans(term, clue, category, wrongs, prompt):
    return {m:{'prompt':prompt,'correct_answer':term,'wrong_answers':wrongs} for m in ['rapid_classification','signal_vs_noise','stroop_test','odd_one_out','memory_cascade','sequence_reverse','pattern_continuation','spatial_recall']}
subroot=APP/'data/observation_banks/creative_arts/worlds/drawing/subcategories'; runtime=APP/'data/content/base_bundle/creative_arts/drawing'
subroot.mkdir(parents=True,exist_ok=True)
if runtime.exists(): shutil.rmtree(runtime)
runtime.mkdir(parents=True,exist_ok=True)
wm_path=APP/'data/observation_banks/creative_arts/worlds/drawing/world_manifest.json'; wm=json.load(open(wm_path))
for sc in wm['subcategories']: sc.update({'implemented_observations':100,'status':'complete','scenario_preferences':prefs})
wm['status']='complete'; json.dump(wm,open(wm_path,'w'),indent=2)
compiled=[]
for subname,pool in subcats.items():
    subid=sid(subname); obs=[]
    for i in range(100):
        term,clue,cat=pool[i%len(pool)]; wrongs=distract(term,pool); label,tier=diff(i); oid=f'creative_arts_drawing_{subid}_{i+1:04d}'; variant=i//len(pool)
        prompt=[f'Which drawing term matches: {clue}?',f'In {subname}, what means {clue}?',f'Name the {cat} described as: {clue}.',f'Which {subname.lower()} concept is {clue}?'][variant%4]
        knowledge={'domain':'drawing','subcategory':subid,'term':term,'concept':term,'definition_clue':clue,'recognized_answer':term,'distractor_family':wrongs,'difficulty_tier':tier,'keywords':[subid,sid(term),sid(cat)],'category':cat}
        transformations=trans(term,clue,cat,wrongs,prompt)
        obs.append({'observation_id':oid,'universe':'creative_arts','world':'drawing','subcategory':subid,'difficulty':{'label':label,'tier':tier},'observation_type':'Rapid Recognition','base_fact':f'{term}: {clue}.','prompt':prompt,'correct_answer':term,'distractors':wrongs,'localization':{'prompt_key':oid+'_prompt','answer_key':oid+'_answer'},'knowledge':knowledge,'mechanic_transformations':transformations,'metadata':{'tags':knowledge['keywords'],'scenario_compatibility':prefs,'deterministic_seed_key':oid,'quality':{'recognition':5,'visual_presentation':5,'fast_comprehension':5,'replayability':5,'educational_value':5,'mobile_readability':5},'source_basis':'Drawing education reference set based on studio drawing fundamentals.','knowledge':knowledge,'mechanic_transformations':transformations}})
        for mech,rule in transformations.items(): compiled.append({'id':f'{oid}_{mech}','observation_id':oid,'universe':'creative_arts','world':'drawing','subcategory':subid,'type':mech,'rules':{'prompt':prompt,'legacy_prompt':prompt,'correct_answer':rule['correct_answer'],'wrong_answers':rule['wrong_answers']},'presentation':{'title':f'Drawing — {subname}','difficulty_tier':tier,'subcategory':subid,'observation_type':mech},'knowledge':knowledge,'metadata':{'source_observation_id':oid,'knowledge':knowledge,'mechanic_transformations':transformations,'built_by':'drawing_state_machine_compiler'}})
    bank={'schema_version':1,'observation_bank_version':'creative_arts.v1.drawing','universe':'creative_arts','world':'drawing','subcategory':subid,'display_name':subname,'constraint_vector':{'core_concept_space':f'Drawing concepts bounded to {subname}.','allowed_elements':['widely taught drawing vocabulary','tools','methods','visual principles','figure and construction concepts'],'forbidden_elements':['software-only image editing','temporary social media styles','obscure artist gossip','opinion-only prompts'],'domain_anchors':['studio drawing fundamentals','art-school drawing exercises','publicly taught illustration vocabulary'],'mechanic_suitability_map':prefs},'scenario_preferences':prefs,'observations':obs}
    json.dump(bank,open(subroot/f'{subid}.json','w'),indent=2,ensure_ascii=False)
json.dump(compiled,open(runtime/'drawing_observation_bank_compiled.json','w'),indent=2,ensure_ascii=False)
print('drawing observations',sum(len(json.load(open(p))['observations']) for p in subroot.glob('*.json')),'compiled',len(compiled))
